# Listening address
agentAddress udp:161,udp6:[::1]:161

# Access control
rocommunity bookcloud_monitor default
rocommunity bookcloud_monitor 10.20.2.2

# System information
sysLocation    Sales Subnet
sysContact     it-team@bookcloud.com

# Include full disk monitoring
includeAllDisks 10%

# Load monitoring
load 12 14 14

# Process monitoring
proc sshd
proc cron
